services:
  homezone-api:
    container_name: homezone-api
    restart: always
    image: node:20.10.0
    ports:
      - 4001:3007
    volumes:
      - ./:/usr/src/homezone
    working_dir: /usr/src/homezone
    networks:
      - monorepo_network
    command: bash -c "rm -rf dist && npm install && npm run build && npm run start:prod"

  homezone-batch:
    container_name: homezone-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4002:3008
    volumes:
      - ./:/usr/src/homezone
    working_dir: /usr/src/homezone
    networks:
      - monorepo_network
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo_network:
    driver: bridge
# homezone-next: localhost:4000 => container:3000
# homezone-api: localhost:4001 => container:3007
# homezone-batch: localhost:4002 => container:3008
# FOR PRODUCTION

# version: '3.3'

# services:
#   homezone-next:
#     container_name: homezone-next
#         build: .
#     restart: always
#     image: node:20.16.0
#     ports:
#       - 4000:3000
#     environment:
#       - PORT=3000

#     volumes:
#       - ./:/usr/src/homezone-next
#     working_dir: /usr/src/homezone-next

#     networks:
#       - client-network

#     command: bash -c "pnpm install && pnpm run build && pnpm run start"

# networks:
#   client-network:
#     driver: bridge

# /...........................
# version: '3.3'

# services:
#   homezone-next:
#     container_name: homezone-next
#     build: .
#     restart: always
#     image: node:20.16.0
#     ports:
#       - '4000:3000'
#     environment:
#       - PORT=3000
#     volumes:
#       - ./:/usr/src/homezone-next
#     working_dir: /usr/src/homezone-next
#     networks:
#       - client-network
#     command: bash -c "yarn && yarn run dev"

# networks:
#   client-network:
#     driver: bridge
